### PR TITLE
REFACTOR and FIX issues in terminal

### PR DESCRIPTION
**Pull request by xabru**
REFACTOR and FIX issues in terminal

### CODE REVIEW

**Comment by xabru** [comment]
in VSCODE press Ctrl + K + 0

**Comment by pedro-hs** [comment]
Hello, thanks for the pull request,
I will made the code review, but first, please

1) Describe which problems this solution fix, or which benefits this improvements brings
2) Remove all your programming personal preferences, keep the actual code pattern
3) All the code including messages, comments must be in English
4) Comeback the indentation and comments
5) Remove your comments
6) Keep in the file just the changes which fix the problems


in VSCODE press Ctrl + K + 0 <-- I use the default vscode config and ctrl + K + 0 and ctrl + k + 0 do nothing

**Comment by xabru** [comment]
This pullrequest is just a way to share some changes I made in the code, you can check it online, I think you can find the differences using the diff included in github. You can close this pull request. regards!.

[https://github.com/pedro-hs/checkbox.sh/pull/11/files](https://github.com/pedro-hs/checkbox.sh/pull/11/files)

**Comment by xabru** [comment]
https://code.visualstudio.com/docs/editor/codebasics#_folding

Fold All (Ctrl+K Ctrl+0) - folds all regions in the editor.
Unfold All (Ctrl+K Ctrl+J) - unfolds all regions in the editor.
Fold Recursively (Ctrl+K Ctrl+[) - folds the innermost uncollapsed region at the cursor and all regions inside that region.
Unfold Recursively (Ctrl+K Ctrl+]) - unfolds the region at the cursor and all regions inside that region.

In my keyboard shortcut setup, I modified Fold and Unfold Recursively by [ALT + A] and [ALT + D] respectively.

Fold Recursively    => Alt + A
Unold Recursively => Alt + D

**Comment by pedro-hs** [comment]
I saw that the main change was wrap the functions and variables into another function
Can you please explain me the benefits or send me an article link explaining this? So I can think in a way to improve the code.

**Pull request closed without merging**
